# -------------------------------
# 🏗️ Etapa de build (gera o .jar)
# -------------------------------
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copia todo o código fonte
COPY . .

# 🩵 Corrige quebras de linha do Windows (CRLF -> LF) e garante execução do wrapper
RUN apt-get update && apt-get install -y dos2unix \
    && dos2unix mvnw \
    && chmod +x mvnw
#Converte qualquer CRLF e garanti que o script seja executável no Linux.
RUN apt-get update && apt-get install -y dos2unix \
    && dos2unix mvnw wait-for-it.sh \
    && chmod +x mvnw wait-for-it.sh

# Build do projeto sem rodar testes
RUN ./mvnw clean package -DskipTests

# -------------------------------
# 🚀 Etapa de runtime (leve e otimizada)
# -------------------------------
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copia o .jar da etapa anterior
COPY --from=build /app/target/*.jar app.jar

# Copia o script wait-for-it.sh e ajusta permissões
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Expõe a porta da API
EXPOSE 8080

# Aguarda o MySQL estar acessível antes de subir a aplicação
ENTRYPOINT ["/wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
